"""fix_refresh_token_expires_at_type

Revision ID: 4b48d6db7760
Revises: f5521aec135d
Create Date: 2026-03-19 02:31:47.188654
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b48d6db7760'
down_revision: Union[str, None] = 'f5521aec135d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="expires_at::timestamp with time zone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
