"""Add service_connectors table

Revision ID: 7f90fbc9c938
Revises: 4b48d6db7760
Create Date: 2026-05-12 15:30:18.501017
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f90fbc9c938'
down_revision: Union[str, None] = '4b48d6db7760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_connectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('connector_type', sa.Enum('HTTP', 'TCP', 'POSTGRESQL', 'REDIS', 'SCRIPT', 'DOCKER', name='connector_type_enum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('expected_status', sa.Integer(), nullable=True),
    sa.Column('script_path', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('custom_config', sa.JSON(), nullable=True),
    sa.Column('last_checked', sa.String(length=50), nullable=True),
    sa.Column('last_state', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_connectors_service_name'), 'service_connectors', ['service_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_connectors_service_name'), table_name='service_connectors')
    op.drop_table('service_connectors')
    # ### end Alembic commands ###
