"""initial_schema

Revision ID: f5521aec135d
Revises: 
Create Date: 2026-03-19 00:39:15.905714
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f5521aec135d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='alert_level_enum'), nullable=False),
    sa.Column('source', sa.Enum('SYSTEM', 'OPEN5GS', 'KAMAILIO', 'PYHSS', 'RAN', 'MANUAL', 'DB', 'REDIS', name='alert_source_enum'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_index('ix_alerts_level_read', 'alerts', ['level', 'is_read'], unique=False)
    op.create_table('service_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.Enum('OPEN5GS', 'KAMAILIO_IMS', 'PYHSS', 'WEBUI', 'DATABASE', 'REDIS', 'RAN_CONNECTOR', 'BACKEND_API', 'NGINX', name='service_name_enum'), nullable=False),
    sa.Column('state', sa.Enum('UP', 'DOWN', 'DEGRADED', 'UNKNOWN', 'MAINTENANCE', name='service_state_enum'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_checked', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_status_service_name'), 'service_status', ['service_name'], unique=True)
    op.create_table('sim_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iccid', sa.String(length=22), nullable=False),
    sa.Column('imsi', sa.String(length=15), nullable=True),
    sa.Column('msisdn', sa.String(length=15), nullable=True),
    sa.Column('ki_placeholder', sa.String(length=32), nullable=True),
    sa.Column('opc_placeholder', sa.String(length=32), nullable=True),
    sa.Column('amf', sa.String(length=8), nullable=True),
    sa.Column('adm', sa.String(length=16), nullable=True),
    sa.Column('sim_type', sa.String(length=20), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'BLOCKED', 'TESTING', 'RETIRED', name='sim_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_cards_iccid'), 'sim_cards', ['iccid'], unique=True)
    op.create_index('ix_sim_cards_status', 'sim_cards', ['status'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imsi', sa.String(length=15), nullable=False),
    sa.Column('msisdn', sa.String(length=15), nullable=False),
    sa.Column('iccid', sa.String(length=22), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'TESTING', name='subscriber_status_enum'), nullable=False),
    sa.Column('apn', sa.String(length=100), nullable=False),
    sa.Column('sim_type', sa.Enum('USIM', 'ISIM', 'UICC', 'VIRTUAL', name='sim_type_enum'), nullable=False),
    sa.Column('profile', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iccid')
    )
    op.create_index(op.f('ix_subscribers_imsi'), 'subscribers', ['imsi'], unique=True)
    op.create_index('ix_subscribers_imsi_msisdn', 'subscribers', ['imsi', 'msisdn'], unique=False)
    op.create_index(op.f('ix_subscribers_msisdn'), 'subscribers', ['msisdn'], unique=True)
    op.create_index('ix_subscribers_status', 'subscribers', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'IMPORT', 'EXPORT', 'STATUS_CHANGE', 'PASSWORD_CHANGE', name='audit_action_enum'), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_user', 'audit_logs', ['action', 'user_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caller_id', sa.Integer(), nullable=True),
    sa.Column('callee_id', sa.Integer(), nullable=True),
    sa.Column('caller_number', sa.String(length=20), nullable=False),
    sa.Column('callee_number', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('call_type', sa.Enum('VOICE', 'VOLTE', 'CS', 'EMERGENCY', name='call_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', 'BUSY', 'NO_ANSWER', 'REJECTED', 'IN_PROGRESS', name='call_status_enum'), nullable=False),
    sa.Column('sip_call_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['callee_id'], ['subscribers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['caller_id'], ['subscribers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_callee_id'), 'calls', ['callee_id'], unique=False)
    op.create_index('ix_calls_caller_callee', 'calls', ['caller_id', 'callee_id'], unique=False)
    op.create_index(op.f('ix_calls_caller_id'), 'calls', ['caller_id'], unique=False)
    op.create_index(op.f('ix_calls_started_at'), 'calls', ['started_at'], unique=False)
    op.create_index('ix_calls_status', 'calls', ['status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('sender_number', sa.String(length=20), nullable=False),
    sa.Column('receiver_number', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('direction', sa.Enum('MO', 'MT', 'INTERNAL', name='sms_direction_enum'), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'FAILED', 'PENDING', 'REJECTED', name='sms_status_enum'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('smsc_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['subscribers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['subscribers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_receiver_id'), 'sms', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_sms_sender_id'), 'sms', ['sender_id'], unique=False)
    op.create_index('ix_sms_sender_receiver', 'sms', ['sender_id', 'receiver_id'], unique=False)
    op.create_index(op.f('ix_sms_sent_at'), 'sms', ['sent_at'], unique=False)
    op.create_index('ix_sms_status', 'sms', ['status'], unique=False)
    op.create_table('subscriber_sim_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('sim_card_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sim_card_id'], ['sim_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_sim_assignments_sim_card_id'), 'subscriber_sim_assignments', ['sim_card_id'], unique=False)
    op.create_index(op.f('ix_subscriber_sim_assignments_subscriber_id'), 'subscriber_sim_assignments', ['subscriber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriber_sim_assignments_subscriber_id'), table_name='subscriber_sim_assignments')
    op.drop_index(op.f('ix_subscriber_sim_assignments_sim_card_id'), table_name='subscriber_sim_assignments')
    op.drop_table('subscriber_sim_assignments')
    op.drop_index('ix_sms_status', table_name='sms')
    op.drop_index(op.f('ix_sms_sent_at'), table_name='sms')
    op.drop_index('ix_sms_sender_receiver', table_name='sms')
    op.drop_index(op.f('ix_sms_sender_id'), table_name='sms')
    op.drop_index(op.f('ix_sms_receiver_id'), table_name='sms')
    op.drop_table('sms')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_calls_status', table_name='calls')
    op.drop_index(op.f('ix_calls_started_at'), table_name='calls')
    op.drop_index(op.f('ix_calls_caller_id'), table_name='calls')
    op.drop_index('ix_calls_caller_callee', table_name='calls')
    op.drop_index(op.f('ix_calls_callee_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_user', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_subscribers_status', table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_msisdn'), table_name='subscribers')
    op.drop_index('ix_subscribers_imsi_msisdn', table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_imsi'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index('ix_sim_cards_status', table_name='sim_cards')
    op.drop_index(op.f('ix_sim_cards_iccid'), table_name='sim_cards')
    op.drop_table('sim_cards')
    op.drop_index(op.f('ix_service_status_service_name'), table_name='service_status')
    op.drop_table('service_status')
    op.drop_index('ix_alerts_level_read', table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
